- name: Demo on Vars
  hosts: all
 
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
    - name: Print URL from Task
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.example.com
